FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \ 
    build-essential \
    cmake \ 
    clang \
    bison \
    flex \
    libreadline-dev \ 
    gawk \
    tcl-dev \
    libffi-dev \ 
    git \
    graphviz \ 
    xdot \
    pkg-config \ 
    python3 \
    python3-dev \
    libpython3-dev \
    libboost-system-dev \
    libboost-python-dev \
    libboost-filesystem-dev \
    zlib1g-dev \
    libboost-dev \ 
    libboost-filesystem-dev \ 
    libboost-thread-dev \
    libboost-program-options-dev \ 
    libboost-python-dev \
    libboost-iostreams-dev \
    libboost-system-dev \
    libboost-chrono-dev \
    libboost-date-time-dev \
    libboost-atomic-dev \
    libboost-regex-dev \
    libpython3-dev \
    libeigen3-dev